export const SerieB = [
  {
    country: "italy",
    league: "serie b",
    team: "ascoli",
    round: 1,
    ground: "home",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 3,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 2,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ternana",
    round: 1,
    ground: "away",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 3,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 2,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "benevento",
    round: 1,
    ground: "home",
    formation: "433",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 1,
    home_goals: 0,
    away_goals: 1,
    first_half_goals: 0,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cosenza",
    round: 1,
    ground: "away",
    formation: "4231",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 1,
    home_goals: 0,
    away_goals: 1,
    first_half_goals: 0,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "brescia",
    round: 1,
    ground: "home",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 2,
    home_goals: 2,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "sudtirol",
    round: 1,
    ground: "away",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 2,
    home_goals: 2,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "modena",
    round: 1,
    ground: "home",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 1,
    home_goals: 0,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "frosinone",
    round: 1,
    ground: "away",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 1,
    home_goals: 0,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "spal",
    round: 1,
    ground: "home",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 4,
    home_goals: 1,
    away_goals: 3,
    first_half_goals: 1,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "reggina",
    round: 1,
    ground: "away",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 4,
    home_goals: 1,
    away_goals: 3,
    first_half_goals: 1,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "venezia",
    round: 1,
    ground: "home",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 3,
    home_goals: 1,
    away_goals: 2,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "genoa",
    round: 1,
    ground: "away",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 3,
    home_goals: 1,
    away_goals: 2,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cittadella",
    round: 1,
    ground: "home",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 7,
    home_goals: 4,
    away_goals: 3,
    first_half_goals: 2,
    second_half_goals: 5,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "pisa",
    round: 1,
    ground: "away",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 7,
    home_goals: 4,
    away_goals: 3,
    first_half_goals: 2,
    second_half_goals: 5,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "como",
    round: 1,
    ground: "home",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cagliari",
    round: 1,
    ground: "away",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "palermo",
    round: 1,
    ground: "home",
    formation: "4231",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 3,
    total_goals: 2,
    home_goals: 2,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "perugia",
    round: 1,
    ground: "away",
    formation: "352",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 2,
    home_goals: 2,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "parma",
    round: 1,
    ground: "home",
    formation: "4231",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 1,
    total_goals: 4,
    home_goals: 2,
    away_goals: 2,
    first_half_goals: 4,
    second_half_goals: 0,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "bari",
    round: 1,
    ground: "away",
    formation: "433",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 1,
    total_goals: 4,
    home_goals: 2,
    away_goals: 2,
    first_half_goals: 4,
    second_half_goals: 0,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cagliari",
    round: 2,
    ground: "home",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 3,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cittadella",
    round: 2,
    ground: "away",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 3,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cosenza",
    round: 2,
    ground: "home",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 3,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "modena",
    round: 2,
    ground: "away",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 3,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "frosinone",
    round: 2,
    ground: "home",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 3,
    home_goals: 3,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "brescia",
    round: 2,
    ground: "away",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 3,
    home_goals: 3,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "pisa",
    round: 2,
    ground: "home",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 4,
    home_goals: 2,
    away_goals: 2,
    first_half_goals: 2,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "como",
    round: 2,
    ground: "away",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 1,
    total_goals: 4,
    home_goals: 2,
    away_goals: 2,
    first_half_goals: 2,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "sudtirol",
    round: 2,
    ground: "home",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 3,
    home_goals: 1,
    away_goals: 2,
    first_half_goals: 0,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "venezia",
    round: 2,
    ground: "away",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 3,
    home_goals: 1,
    away_goals: 2,
    first_half_goals: 0,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ternana",
    round: 2,
    ground: "home",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "reggina",
    round: 2,
    ground: "away",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ascoli",
    round: 2,
    ground: "home",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 2,
    second_half_goals: 0,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "spal",
    round: 2,
    ground: "away",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 2,
    second_half_goals: 0,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "genoa",
    round: 2,
    ground: "home",
    formation: "442",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "benevento",
    round: 2,
    ground: "away",
    formation: "352",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "perugia",
    round: 2,
    ground: "home",
    formation: "352",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "parma",
    round: 2,
    ground: "away",
    formation: "4231",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "bari",
    round: 2,
    ground: "home",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "palermo",
    round: 2,
    ground: "away",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "como",
    round: 3,
    ground: "home",
    formation: "442",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 1,
    home_goals: 0,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "brescia",
    round: 3,
    ground: "away",
    formation: "442",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 1,
    home_goals: 0,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "benevento",
    round: 3,
    ground: "home",
    formation: "352",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 3,
    total_goals: 3,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "frosinone",
    round: 3,
    ground: "away",
    formation: "4231",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 0,
    total_goals: 3,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cittadella",
    round: 3,
    ground: "home",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "venezia",
    round: 3,
    ground: "away",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "parma",
    round: 3,
    ground: "home",
    formation: "4231",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 3,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cosenza",
    round: 3,
    ground: "away",
    formation: "4231",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "perugia",
    round: 3,
    ground: "home",
    formation: "352",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 4,
    home_goals: 1,
    away_goals: 3,
    first_half_goals: 1,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "bari",
    round: 3,
    ground: "away",
    formation: "442",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 3,
    total_goals: 4,
    home_goals: 1,
    away_goals: 3,
    first_half_goals: 1,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "pisa",
    round: 3,
    ground: "home",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 1,
    home_goals: 0,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "genoa",
    round: 3,
    ground: "away",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 1,
    home_goals: 0,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "reggina",
    round: 3,
    ground: "home",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 4,
    home_goals: 4,
    away_goals: 0,
    first_half_goals: 2,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "sudtirol",
    round: 3,
    ground: "away",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 4,
    home_goals: 4,
    away_goals: 0,
    first_half_goals: 2,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "modena",
    round: 3,
    ground: "home",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 5,
    home_goals: 4,
    away_goals: 1,
    first_half_goals: 2,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ternana",
    round: 3,
    ground: "away",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 5,
    home_goals: 4,
    away_goals: 1,
    first_half_goals: 2,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "palermo",
    round: 3,
    ground: "home",
    formation: "4231",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 5,
    home_goals: 2,
    away_goals: 3,
    first_half_goals: 3,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ascoli",
    round: 3,
    ground: "away",
    formation: "433",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 3,
    total_goals: 5,
    home_goals: 2,
    away_goals: 3,
    first_half_goals: 3,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "spal",
    round: 3,
    ground: "home",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cagliari",
    round: 3,
    ground: "away",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "sudtirol",
    round: 4,
    ground: "home",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 2,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 2,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "pisa",
    round: 4,
    ground: "away",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 2,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 2,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "genoa",
    round: 4,
    ground: "home",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 1,
    total_goals: 6,
    home_goals: 3,
    away_goals: 3,
    first_half_goals: 4,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "parma",
    round: 4,
    ground: "away",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 6,
    home_goals: 3,
    away_goals: 3,
    first_half_goals: 4,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ascoli",
    round: 4,
    ground: "home",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cittadella",
    round: 4,
    ground: "away",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "bari",
    round: 4,
    ground: "home",
    formation: "442",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 4,
    home_goals: 2,
    away_goals: 2,
    first_half_goals: 2,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "spal",
    round: 4,
    ground: "away",
    formation: "442",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 4,
    home_goals: 2,
    away_goals: 2,
    first_half_goals: 2,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "brescia",
    round: 4,
    ground: "home",
    formation: "433",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 3,
    total_goals: 3,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 3,
    second_half_goals: 0,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "perugia",
    round: 4,
    ground: "away",
    formation: "352",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 3,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 3,
    second_half_goals: 0,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "frosinone",
    round: 4,
    ground: "home",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 2,
    home_goals: 2,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "como",
    round: 4,
    ground: "away",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 2,
    home_goals: 2,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "reggina",
    round: 4,
    ground: "home",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 3,
    home_goals: 3,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "palermo",
    round: 4,
    ground: "away",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 3,
    home_goals: 3,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ternana",
    round: 4,
    ground: "home",
    formation: "433",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cosenza",
    round: 4,
    ground: "away",
    formation: "4231",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "venezia",
    round: 4,
    ground: "home",
    formation: "433",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 0,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "benevento",
    round: 4,
    ground: "away",
    formation: "352",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cagliari",
    round: 4,
    ground: "home",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "modena",
    round: 4,
    ground: "away",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "spal",
    round: 5,
    ground: "home",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 2,
    home_goals: 2,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "venezia",
    round: 5,
    ground: "away",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 2,
    home_goals: 2,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "perugia",
    round: 5,
    ground: "home",
    formation: "352",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ascoli",
    round: 5,
    ground: "away",
    formation: "433",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 0,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "benevento",
    round: 5,
    ground: "home",
    formation: "352",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cagliari",
    round: 5,
    ground: "away",
    formation: "433",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 3,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cittadella",
    round: 5,
    ground: "home",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "frosinone",
    round: 5,
    ground: "away",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "como",
    round: 5,
    ground: "home",
    formation: "442",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 0,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "sudtirol",
    round: 5,
    ground: "away",
    formation: "352",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cosenza",
    round: 5,
    ground: "home",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 1,
    home_goals: 0,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "bari",
    round: 5,
    ground: "away",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 3,
    total_goals: 1,
    home_goals: 0,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "modena",
    round: 5,
    ground: "home",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 4,
    home_goals: 1,
    away_goals: 3,
    first_half_goals: 2,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "brescia",
    round: 5,
    ground: "away",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 4,
    home_goals: 1,
    away_goals: 3,
    first_half_goals: 2,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "parma",
    round: 5,
    ground: "home",
    formation: "4231",
    opp_formation: "541",
    opp_def: 5,
    opp_mid: 4,
    points: 0,
    total_goals: 5,
    home_goals: 2,
    away_goals: 3,
    first_half_goals: 1,
    second_half_goals: 4,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ternana",
    round: 5,
    ground: "away",
    formation: "541",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 3,
    total_goals: 5,
    home_goals: 2,
    away_goals: 3,
    first_half_goals: 1,
    second_half_goals: 4,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "pisa",
    round: 5,
    ground: "home",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 1,
    home_goals: 0,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "reggina",
    round: 5,
    ground: "away",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 1,
    home_goals: 0,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "palermo",
    round: 5,
    ground: "home",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "genoa",
    round: 5,
    ground: "away",
    formation: "442",
    opp_formation: "443",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ternana",
    round: 6,
    ground: "home",
    formation: "433",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 3,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "perugia",
    round: 6,
    ground: "away",
    formation: "352",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "genoa",
    round: 6,
    ground: "home",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "modena",
    round: 6,
    ground: "away",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ascoli",
    round: 6,
    ground: "home",
    formation: "433",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 4,
    home_goals: 1,
    away_goals: 3,
    first_half_goals: 2,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "parma",
    round: 6,
    ground: "away",
    formation: "4231",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 4,
    home_goals: 1,
    away_goals: 3,
    first_half_goals: 2,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cagliari",
    round: 6,
    ground: "home",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 1,
    home_goals: 0,
    away_goals: 1,
    first_half_goals: 0,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "bari",
    round: 6,
    ground: "away",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 1,
    home_goals: 0,
    away_goals: 1,
    first_half_goals: 0,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "como",
    round: 6,
    ground: "home",
    formation: "442",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 6,
    home_goals: 3,
    away_goals: 3,
    first_half_goals: 2,
    second_half_goals: 4,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "spal",
    round: 6,
    ground: "away",
    formation: "442",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 6,
    home_goals: 3,
    away_goals: 3,
    first_half_goals: 2,
    second_half_goals: 4,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "frosinone",
    round: 6,
    ground: "home",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "palermo",
    round: 6,
    ground: "away",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "reggina",
    round: 6,
    ground: "home",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 3,
    home_goals: 3,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cittadella",
    round: 6,
    ground: "away",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 3,
    home_goals: 3,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "sudtirol",
    round: 6,
    ground: "home",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cosenza",
    round: 6,
    ground: "away",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "venezia",
    round: 6,
    ground: "home",
    formation: "352",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 2,
    second_half_goals: 0,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "pisa",
    round: 6,
    ground: "away",
    formation: "442",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 2,
    second_half_goals: 0,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "brescia",
    round: 6,
    ground: "home",
    formation: "433",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 3,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "benevento",
    round: 6,
    ground: "away",
    formation: "352",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "benevento",
    round: 7,
    ground: "home",
    formation: "343",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ascoli",
    round: 7,
    ground: "away",
    formation: "352",
    opp_formation: "343",
    opp_def: 3,
    opp_mid: 4,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "perugia",
    round: 7,
    ground: "home",
    formation: "352",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 4,
    home_goals: 1,
    away_goals: 3,
    first_half_goals: 1,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "pisa",
    round: 7,
    ground: "away",
    formation: "442",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 3,
    total_goals: 4,
    home_goals: 1,
    away_goals: 3,
    first_half_goals: 1,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "bari",
    round: 7,
    ground: "home",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 8,
    home_goals: 6,
    away_goals: 3,
    first_half_goals: 3,
    second_half_goals: 5,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "brescia",
    round: 7,
    ground: "away",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 8,
    home_goals: 6,
    away_goals: 3,
    first_half_goals: 3,
    second_half_goals: 5,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cagliari",
    round: 7,
    ground: "home",
    formation: "433",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 0,
    total_goals: 5,
    home_goals: 1,
    away_goals: 4,
    first_half_goals: 1,
    second_half_goals: 4,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "venezia",
    round: 7,
    ground: "away",
    formation: "352",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 5,
    home_goals: 1,
    away_goals: 4,
    first_half_goals: 1,
    second_half_goals: 4,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cittadella",
    round: 7,
    ground: "home",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ternana",
    round: 7,
    ground: "away",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "modena",
    round: 7,
    ground: "home",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "reggina",
    round: 7,
    ground: "away",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "palermo",
    round: 7,
    ground: "home",
    formation: "4231",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 0,
    total_goals: 1,
    home_goals: 0,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "sudtirol",
    round: 7,
    ground: "away",
    formation: "352",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 3,
    total_goals: 1,
    home_goals: 0,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "parma",
    round: 7,
    ground: "home",
    formation: "4231",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 2,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "frosinone",
    round: 7,
    ground: "away",
    formation: "433",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 2,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "spal",
    round: 7,
    ground: "home",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "genoa",
    round: 7,
    ground: "away",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cosenza",
    round: 7,
    ground: "home",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 4,
    home_goals: 3,
    away_goals: 1,
    first_half_goals: 3,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "como",
    round: 7,
    ground: "away",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 4,
    home_goals: 3,
    away_goals: 1,
    first_half_goals: 3,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "como",
    round: 8,
    ground: "home",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 3,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "perugia",
    round: 8,
    ground: "away",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "sudtirol",
    round: 8,
    ground: "home",
    formation: "442",
    opp_formation: "343",
    opp_def: 3,
    opp_mid: 4,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "benevento",
    round: 8,
    ground: "away",
    formation: "343",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "frosinone",
    round: 8,
    ground: "home",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 2,
    home_goals: 2,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "spal",
    round: 8,
    ground: "away",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 2,
    home_goals: 2,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "reggina",
    round: 8,
    ground: "home",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 3,
    home_goals: 3,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cosenza",
    round: 8,
    ground: "away",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 3,
    home_goals: 3,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ascoli",
    round: 8,
    ground: "home",
    formation: "352",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 3,
    home_goals: 1,
    away_goals: 2,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "modena",
    round: 8,
    ground: "away",
    formation: "433",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 3,
    total_goals: 3,
    home_goals: 1,
    away_goals: 2,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "brescia",
    round: 8,
    ground: "home",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cittadella",
    round: 8,
    ground: "away",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "pisa",
    round: 8,
    ground: "home",
    formation: "4231",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "parma",
    round: 8,
    ground: "away",
    formation: "4231",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ternana",
    round: 8,
    ground: "home",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 3,
    home_goals: 3,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 3,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "palermo",
    round: 8,
    ground: "away",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 3,
    home_goals: 3,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 3,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "venezia",
    round: 8,
    ground: "home",
    formation: "352",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 3,
    home_goals: 1,
    away_goals: 2,
    first_half_goals: 0,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "bari",
    round: 8,
    ground: "away",
    formation: "442",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 3,
    total_goals: 3,
    home_goals: 1,
    away_goals: 2,
    first_half_goals: 0,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "genoa",
    round: 8,
    ground: "home",
    formation: "4231",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cagliari",
    round: 8,
    ground: "away",
    formation: "433",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "perugia",
    round: 9,
    ground: "home",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 3,
    home_goals: 1,
    away_goals: 2,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "sudtirol",
    round: 9,
    ground: "away",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 3,
    total_goals: 3,
    home_goals: 1,
    away_goals: 2,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "bari",
    round: 9,
    ground: "home",
    formation: "442",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 0,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ascoli",
    round: 9,
    ground: "away",
    formation: "352",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "benevento",
    round: 9,
    ground: "home",
    formation: "343",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 5,
    home_goals: 2,
    away_goals: 3,
    first_half_goals: 2,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ternana",
    round: 9,
    ground: "away",
    formation: "433",
    opp_formation: "343",
    opp_def: 3,
    opp_mid: 4,
    points: 3,
    total_goals: 5,
    home_goals: 2,
    away_goals: 3,
    first_half_goals: 2,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cagliari",
    round: 9,
    ground: "home",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 3,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 2,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "brescia",
    round: 9,
    ground: "away",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 3,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 2,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cittadella",
    round: 9,
    ground: "home",
    formation: "442",
    opp_formation: "532",
    opp_def: 5,
    opp_mid: 3,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "spal",
    round: 9,
    ground: "away",
    formation: "532",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 2,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cosenza",
    round: 9,
    ground: "home",
    formation: "352",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 3,
    home_goals: 1,
    away_goals: 2,
    first_half_goals: 3,
    second_half_goals: 0,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "genoa",
    round: 9,
    ground: "away",
    formation: "4231",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 3,
    total_goals: 3,
    home_goals: 1,
    away_goals: 2,
    first_half_goals: 3,
    second_half_goals: 0,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "modena",
    round: 9,
    ground: "home",
    formation: "442",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 6,
    home_goals: 5,
    away_goals: 1,
    first_half_goals: 3,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "como",
    round: 9,
    ground: "away",
    formation: "442",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 6,
    home_goals: 5,
    away_goals: 1,
    first_half_goals: 3,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "palermo",
    round: 9,
    ground: "home",
    formation: "343",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 1,
    total_goals: 6,
    home_goals: 3,
    away_goals: 3,
    first_half_goals: 3,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "pisa",
    round: 9,
    ground: "away",
    formation: "4231",
    opp_formation: "343",
    opp_def: 3,
    opp_mid: 4,
    points: 1,
    total_goals: 6,
    home_goals: 3,
    away_goals: 3,
    first_half_goals: 3,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "parma",
    round: 9,
    ground: "home",
    formation: "4231",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 2,
    home_goals: 2,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "reggina",
    round: 9,
    ground: "away",
    formation: "433",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 2,
    home_goals: 2,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "venezia",
    round: 9,
    ground: "home",
    formation: "352",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 4,
    home_goals: 1,
    away_goals: 3,
    first_half_goals: 1,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "frosinone",
    round: 9,
    ground: "away",
    formation: "4231",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 3,
    total_goals: 4,
    home_goals: 1,
    away_goals: 3,
    first_half_goals: 1,
    second_half_goals: 3,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ascoli",
    round: 10,
    ground: "home",
    formation: "352",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 3,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cagliari",
    round: 10,
    ground: "away",
    formation: "433",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 0,
    total_goals: 3,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "palermo",
    round: 10,
    ground: "home",
    formation: "352",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cittadella",
    round: 10,
    ground: "away",
    formation: "4231",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "pisa",
    round: 10,
    ground: "home",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 6,
    home_goals: 4,
    away_goals: 2,
    first_half_goals: 2,
    second_half_goals: 4,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "modena",
    round: 10,
    ground: "away",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 6,
    home_goals: 4,
    away_goals: 2,
    first_half_goals: 2,
    second_half_goals: 4,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ternana",
    round: 10,
    ground: "home",
    formation: "433",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 3,
    home_goals: 1,
    away_goals: 2,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "genoa",
    round: 10,
    ground: "away",
    formation: "4231",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 3,
    total_goals: 3,
    home_goals: 1,
    away_goals: 2,
    first_half_goals: 1,
    second_half_goals: 2,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "brescia",
    round: 10,
    ground: "home",
    formation: "442",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "venezia",
    round: 10,
    ground: "away",
    formation: "352",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "como",
    round: 10,
    ground: "home",
    formation: "442",
    opp_formation: "343",
    opp_def: 3,
    opp_mid: 4,
    points: 3,
    total_goals: 3,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 3,
    second_half_goals: 0,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "benevento",
    round: 10,
    ground: "away",
    formation: "343",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 3,
    home_goals: 2,
    away_goals: 1,
    first_half_goals: 3,
    second_half_goals: 0,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "frosinone",
    round: 10,
    ground: "home",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "bari",
    round: 10,
    ground: "away",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "reggina",
    round: 10,
    ground: "home",
    formation: "433",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 0,
    total_goals: 5,
    home_goals: 2,
    away_goals: 3,
    first_half_goals: 1,
    second_half_goals: 4,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "perugia",
    round: 10,
    ground: "away",
    formation: "352",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 1,
    total_goals: 5,
    home_goals: 2,
    away_goals: 3,
    first_half_goals: 1,
    second_half_goals: 4,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "spal",
    round: 10,
    ground: "home",
    formation: "343",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 3,
    total_goals: 5,
    home_goals: 5,
    away_goals: 0,
    first_half_goals: 2,
    second_half_goals: 3,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cosenza",
    round: 10,
    ground: "away",
    formation: "352",
    opp_formation: "343",
    opp_def: 3,
    opp_mid: 4,
    points: 0,
    total_goals: 5,
    home_goals: 5,
    away_goals: 0,
    first_half_goals: 2,
    second_half_goals: 3,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "sudtirol",
    round: 10,
    ground: "home",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 3,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "parma",
    round: 10,
    ground: "away",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "perugia",
    round: 11,
    ground: "home",
    formation: "352",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cittadella",
    round: 11,
    ground: "away",
    formation: "442",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 3,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "genoa",
    round: 11,
    ground: "home",
    formation: "4231",
    opp_formation: "451",
    opp_def: 4,
    opp_mid: 5,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "brescia",
    round: 11,
    ground: "away",
    formation: "451",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "benevento",
    round: 11,
    ground: "home",
    formation: "343",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "pisa",
    round: 11,
    ground: "away",
    formation: "442",
    opp_formation: "343",
    opp_def: 3,
    opp_mid: 4,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cagliari",
    round: 11,
    ground: "home",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 2,
    second_half_goals: 0,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "reggina",
    round: 11,
    ground: "away",
    formation: "433",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 2,
    second_half_goals: 0,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "cosenza",
    round: 11,
    ground: "home",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 0,
    total_goals: 3,
    home_goals: 1,
    away_goals: 2,
    first_half_goals: 2,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "frosinone",
    round: 11,
    ground: "away",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 3,
    total_goals: 3,
    home_goals: 1,
    away_goals: 2,
    first_half_goals: 2,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "modena",
    round: 11,
    ground: "home",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 0,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 2,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "palermo",
    round: 11,
    ground: "away",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 2,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "parma",
    round: 11,
    ground: "home",
    formation: "4231",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 3,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "como",
    round: 11,
    ground: "away",
    formation: "442",
    opp_formation: "4231",
    opp_def: 4,
    opp_mid: 2,
    points: 0,
    total_goals: 1,
    home_goals: 1,
    away_goals: 0,
    first_half_goals: 1,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "spal",
    round: 11,
    ground: "home",
    formation: "352",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "sudtirol",
    round: 11,
    ground: "away",
    formation: "442",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 1,
    total_goals: 2,
    home_goals: 1,
    away_goals: 1,
    first_half_goals: 1,
    second_half_goals: 1,
    btts: 1,
  },
  {
    country: "italy",
    league: "serie b",
    team: "venezia",
    round: 11,
    ground: "home",
    formation: "352",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 0,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ascoli",
    round: 11,
    ground: "away",
    formation: "352",
    opp_formation: "352",
    opp_def: 3,
    opp_mid: 5,
    points: 3,
    total_goals: 2,
    home_goals: 0,
    away_goals: 2,
    first_half_goals: 0,
    second_half_goals: 2,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "bari",
    round: 11,
    ground: "home",
    formation: "442",
    opp_formation: "433",
    opp_def: 4,
    opp_mid: 3,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },
  {
    country: "italy",
    league: "serie b",
    team: "ternana",
    round: 11,
    ground: "away",
    formation: "433",
    opp_formation: "442",
    opp_def: 4,
    opp_mid: 4,
    points: 1,
    total_goals: 0,
    home_goals: 0,
    away_goals: 0,
    first_half_goals: 0,
    second_half_goals: 0,
    btts: 0,
  },


]