export const SerieB = [
  {
    homeTeam: 'Pisa',
    awayTeam: 'Ascoli',
    homeGoals: 2,
    awayGoals: 0,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '433',
    awayFormation: '352',
    firstGoalTime: 0,
    btts: 0
  },
  {
    homeTeam: 'Cittadella',
    awayTeam: 'Bari',
    homeGoals: 0,
    awayGoals: 3,
    totalGoals: 3,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 2,
    halfTimeGoals: 2,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '442',
    firstGoalTime: 0,
    btts: 0
  },
  {
    homeTeam: 'Cosenza',
    awayTeam: 'Brescia',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 2,
    homeFormation: '433',
    awayFormation: '442',
    firstGoalTime: 0,
    btts: 1
  },
  {
    homeTeam: 'Genoa',
    awayTeam: 'Sudtirol',
    homeGoals: 2,
    awayGoals: 0,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 2,
    homeFormation: '4231',
    awayFormation: '451',
    firstGoalTime: 0,
    btts: 0
  },
  {
    homeTeam: 'Modena',
    awayTeam: 'Venezia',
    homeGoals: 2,
    awayGoals: 2,
    totalGoals: 4,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 3,
    homeFormation: '442',
    awayFormation: '352',
    firstGoalTime: 0,
    btts: 1
  },
  {
    homeTeam: 'Perugia',
    awayTeam: 'Spal',
    homeGoals: 0,
    awayGoals: 0,
    totalGoals: 0,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 0,
    homeFormation: '352',
    awayFormation: '352',
    firstGoalTime: 0,
    btts: 0
  },
  {
    homeTeam: 'Reggina',
    awayTeam: 'Frosinone',
    homeGoals: 0,
    awayGoals: 3,
    totalGoals: 3,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 2,
    homeFormation: '433',
    awayFormation: '433',
    firstGoalTime: 0,
    btts: 0
  },
  {
    homeTeam: 'Parma',
    awayTeam: 'Benevento',
    homeGoals: 0,
    awayGoals: 1,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '4231',
    awayFormation: '433',
    firstGoalTime: 0,
    btts: 0
  },
  {
    homeTeam: 'Ternana',
    awayTeam: 'Cagliari',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '442',
    awayFormation: '442',
    firstGoalTime: 0,
    btts: 0
  },
  {
    homeTeam: 'Benevento',
    awayTeam: 'Palermo',
    homeGoals: 0,
    awayGoals: 1,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 1,
    homeFormation: '433',
    awayFormation: '352',
    firstGoalTime: 0,
    btts: 0
  },
  {
    homeTeam: 'Ascoli',
    awayTeam: 'Como',
    homeGoals: 3,
    awayGoals: 3,
    totalGoals: 6,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 2,
    halfTimeGoals: 3,
    secondHalfGoals: 3,
    homeFormation: '352',
    awayFormation: '442',
    firstGoalTime: 0,
    btts: 1
  },
  {
    homeTeam: 'Bari',
    awayTeam: 'Pisa',
    homeGoals: 0,
    awayGoals: 0,
    totalGoals: 0,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 0,
    homeFormation: '442',
    awayFormation: '352',
    firstGoalTime: 0,
    btts: 0
  },
  {
    homeTeam: 'Brescia',
    awayTeam: 'Reggina',
    homeGoals: 0,
    awayGoals: 2,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 2,
    halfTimeGoals: 2,
    secondHalfGoals: 0,
    homeFormation: '442',
    awayFormation: '433',
    firstGoalTime: 0,
    btts: 0
  },
  {
    homeTeam: 'Cosenza',
    awayTeam: 'Perugia',
    homeGoals: 0,
    awayGoals: 0,
    totalGoals: 0,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 0,
    homeFormation: '433',
    awayFormation: '352',
    firstGoalTime: 0,
    btts: 0
  },
  {
    homeTeam: 'Genoa',
    awayTeam: 'Cittadella',
    homeGoals: 0,
    awayGoals: 1,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 1,
    homeFormation: '4231',
    awayFormation: '442',
    firstGoalTime: 0,
    btts: 0
  },
  {
    homeTeam: 'Sudtirol',
    awayTeam: 'Frosinone',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '433',
    firstGoalTime: 0,
    btts: 1
  },
  {
    homeTeam: 'Spal',
    awayTeam: 'Modena',
    homeGoals: 2,
    awayGoals: 3,
    totalGoals: 5,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 4,
    homeFormation: '352',
    awayFormation: '433',
    firstGoalTime: 0,
    btts: 1
  },
  {
    homeTeam: 'Cagliari',
    awayTeam: 'Parma',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '4231',
    firstGoalTime: 0,
    btts: 1
  },
  {
    homeTeam: 'Venezia',
    awayTeam: 'Ternana',
    homeGoals: 2,
    awayGoals: 1,
    totalGoals: 3,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 3,
    secondHalfGoals: 0,
    homeFormation: '352',
    awayFormation: '442',
    firstGoalTime: 0,
    btts: 1
  },
  {
    homeTeam: 'Palermo',
    awayTeam: 'Venezia',
    homeGoals: 0,
    awayGoals: 1,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 1,
    homeFormation: '433',
    awayFormation: '352',
    btts: 0
  },
  {
    homeTeam: 'Brescia',
    awayTeam: 'Spal',
    homeGoals: 2,
    awayGoals: 0,
    totalGoals: 2,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 2,
    secondHalfGoals: 0,
    homeFormation: '433',
    awayFormation: '352',
    btts: 0
  },
  {
    homeTeam: 'Cittadella',
    awayTeam: 'Cosenza',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Como',
    awayTeam: 'Bari',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Frosinone',
    awayTeam: 'Cagliari',
    homeGoals: 2,
    awayGoals: 2,
    totalGoals: 4,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 2,
    secondHalfGoals: 2,
    homeFormation: '442',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Perugia',
    awayTeam: 'Genoa',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 1,
    homeFormation: '352',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Sudtirol',
    awayTeam: 'Ascoli',
    homeGoals: 2,
    awayGoals: 2,
    totalGoals: 4,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 3,
    homeFormation: '442',
    awayFormation: '352',
    btts: 1
  },
  {
    homeTeam: 'Reggina',
    awayTeam: 'Benevento',
    homeGoals: 2,
    awayGoals: 2,
    totalGoals: 4,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 2,
    secondHalfGoals: 2,
    homeFormation: '433',
    awayFormation: '352',
    btts: 1
  },
  {
    homeTeam: 'Pisa',
    awayTeam: 'Ternana',
    homeGoals: 3,
    awayGoals: 1,
    totalGoals: 4,
    homeHalfTimeGoals: 3,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 4,
    secondHalfGoals: 0,
    homeFormation: '433',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Parma',
    awayTeam: 'Modena',
    homeGoals: 1,
    awayGoals: 2,
    totalGoals: 3,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 2,
    halfTimeGoals: 2,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Genoa',
    awayTeam: 'Como',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '451',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Ternana',
    awayTeam: 'Brescia',
    homeGoals: 0,
    awayGoals: 0,
    totalGoals: 0,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 0,
    homeFormation: '433',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Bari',
    awayTeam: 'Sudtirol',
    homeGoals: 2,
    awayGoals: 2,
    totalGoals: 4,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 2,
    halfTimeGoals: 3,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Cagliari',
    awayTeam: 'Pisa',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 2,
    homeFormation: '433',
    awayFormation: '343',
    btts: 1
  },
  {
    homeTeam: 'Cosenza',
    awayTeam: 'Palermo',
    homeGoals: 3,
    awayGoals: 2,
    totalGoals: 5,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 2,
    secondHalfGoals: 3,
    homeFormation: '433',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Modena',
    awayTeam: 'Perugia',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 2,
    secondHalfGoals: 0,
    homeFormation: '442',
    awayFormation: '352',
    btts: 1
  },
  {
    homeTeam: 'Parma',
    awayTeam: 'Cittadella',
    homeGoals: 3,
    awayGoals: 1,
    totalGoals: 4,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 3,
    homeFormation: '442',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Spal',
    awayTeam: 'Benevento',
    homeGoals: 1,
    awayGoals: 2,
    totalGoals: 3,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 2,
    homeFormation: '352',
    awayFormation: '352',
    btts: 1
  },
  {
    homeTeam: 'Venezia',
    awayTeam: 'Reggina',
    homeGoals: 1,
    awayGoals: 2,
    totalGoals: 3,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 2,
    homeFormation: '352',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Ascoli',
    awayTeam: 'Frosinone',
    homeGoals: 0,
    awayGoals: 1,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 1,
    homeFormation: '352',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Reggina',
    awayTeam: 'Genoa',
    homeGoals: 2,
    awayGoals: 1,
    totalGoals: 3,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 2,
    secondHalfGoals: 1,
    homeFormation: '433',
    awayFormation: '4231',
    btts: 1
  },
  {
    homeTeam: 'Como',
    awayTeam: 'Venezia',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '352',
    btts: 0
  },
  {
    homeTeam: 'Frosinone',
    awayTeam: 'Perugia',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '4231',
    awayFormation: '352',
    btts: 0
  },
  {
    homeTeam: 'Palermo',
    awayTeam: 'Parma',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 1,
    homeFormation: '433',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Benevento',
    awayTeam: 'Bari',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '352',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Brescia',
    awayTeam: 'Ascoli',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 2,
    homeFormation: '442',
    awayFormation: '352',
    btts: 1
  },
  {
    homeTeam: 'Cittadella',
    awayTeam: 'Modena',
    homeGoals: 0,
    awayGoals: 0,
    totalGoals: 0,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 0,
    homeFormation: '442',
    awayFormation: '352',
    btts: 0
  },
  {
    homeTeam: 'Pisa',
    awayTeam: 'Cosenza',
    homeGoals: 3,
    awayGoals: 1,
    totalGoals: 4,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 2,
    secondHalfGoals: 2,
    homeFormation: '442',
    awayFormation: '4231',
    btts: 1
  },
  {
    homeTeam: 'Sudtirol',
    awayTeam: 'Cagliari',
    homeGoals: 2,
    awayGoals: 2,
    totalGoals: 4,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 2,
    secondHalfGoals: 2,
    homeFormation: '442',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Ternana',
    awayTeam: 'Spal',
    homeGoals: 0,
    awayGoals: 0,
    totalGoals: 0,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 0,
    homeFormation: '433',
    awayFormation: '352',
    btts: 0
  },
  {
    homeTeam: 'Perugia',
    awayTeam: 'Cittadella',
    homeGoals: 0,
    awayGoals: 2,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '352',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Genoa',
    awayTeam: 'Brescia',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '4231',
    awayFormation: '451',
    btts: 1
  },
  {
    homeTeam: 'Benevento',
    awayTeam: 'Pisa',
    homeGoals: 0,
    awayGoals: 0,
    totalGoals: 0,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 0,
    homeFormation: '343',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Cagliari',
    awayTeam: 'Reggina',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 2,
    secondHalfGoals: 0,
    homeFormation: '433',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Cosenza',
    awayTeam: 'Frosinone',
    homeGoals: 1,
    awayGoals: 2,
    totalGoals: 3,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 2,
    secondHalfGoals: 1,
    homeFormation: '4231',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Modena',
    awayTeam: 'Palermo',
    homeGoals: 0,
    awayGoals: 2,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 2,
    halfTimeGoals: 2,
    secondHalfGoals: 0,
    homeFormation: '442',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Parma',
    awayTeam: 'Como',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '4231',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Spal',
    awayTeam: 'Sudtirol',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '352',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Venezia',
    awayTeam: 'Ascoli',
    homeGoals: 0,
    awayGoals: 2,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 2,
    homeFormation: '352',
    awayFormation: '352',
    btts: 0
  },
  {
    homeTeam: 'Bari',
    awayTeam: 'Ternana',
    homeGoals: 0,
    awayGoals: 0,
    totalGoals: 0,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 0,
    homeFormation: '442',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Ascoli',
    awayTeam: 'Cagliari',
    homeGoals: 2,
    awayGoals: 1,
    totalGoals: 3,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 2,
    homeFormation: '352',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Palermo',
    awayTeam: 'Cittadella',
    homeGoals: 0,
    awayGoals: 0,
    totalGoals: 0,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 0,
    homeFormation: '352',
    awayFormation: '4231',
    btts: 0
  },
  {
    homeTeam: 'Pisa',
    awayTeam: 'Modena',
    homeGoals: 4,
    awayGoals: 2,
    totalGoals: 6,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 2,
    secondHalfGoals: 4,
    homeFormation: '4231',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Ternana',
    awayTeam: 'Genoa',
    homeGoals: 1,
    awayGoals: 2,
    totalGoals: 3,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 2,
    homeFormation: '433',
    awayFormation: '4231',
    btts: 1
  },
  {
    homeTeam: 'Brescia',
    awayTeam: 'Venezia',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '352',
    btts: 1
  },
  {
    homeTeam: 'Como',
    awayTeam: 'Benevento',
    homeGoals: 2,
    awayGoals: 1,
    totalGoals: 3,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 3,
    secondHalfGoals: 0,
    homeFormation: '442',
    awayFormation: '343',
    btts: 1
  },
  {
    homeTeam: 'Frosinone',
    awayTeam: 'Bari',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 1,
    homeFormation: '4231',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Reggina',
    awayTeam: 'Perugia',
    homeGoals: 2,
    awayGoals: 3,
    totalGoals: 5,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 4,
    homeFormation: '433',
    awayFormation: '352',
    btts: 1
  },
  {
    homeTeam: 'Spal',
    awayTeam: 'Cosenza',
    homeGoals: 5,
    awayGoals: 0,
    totalGoals: 5,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 2,
    secondHalfGoals: 3,
    homeFormation: '352',
    awayFormation: '352',
    btts: 0
  },
  {
    homeTeam: 'Sudtirol',
    awayTeam: 'Parma',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '442',
    awayFormation: '4231',
    btts: 0
  },
  {
    homeTeam: 'Perugia',
    awayTeam: 'Sudtirol',
    homeGoals: 1,
    awayGoals: 2,
    totalGoals: 3,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 2,
    homeFormation: '4231',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Bari',
    awayTeam: 'Ascoli',
    homeGoals: 0,
    awayGoals: 2,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 2,
    homeFormation: '442',
    awayFormation: '352',
    btts: 0
  },
  {
    homeTeam: 'Benevento',
    awayTeam: 'Ternana',
    homeGoals: 2,
    awayGoals: 3,
    totalGoals: 5,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 2,
    secondHalfGoals: 3,
    homeFormation: '343',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Cagliari',
    awayTeam: 'Brescia',
    homeGoals: 2,
    awayGoals: 1,
    totalGoals: 3,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 2,
    secondHalfGoals: 1,
    homeFormation: '433',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Cittadella',
    awayTeam: 'Spal',
    homeGoals: 0,
    awayGoals: 0,
    totalGoals: 0,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 0,
    homeFormation: '442',
    awayFormation: '532',
    btts: 0
  },
  {
    homeTeam: 'Cosenza',
    awayTeam: 'Genoa',
    homeGoals: 1,
    awayGoals: 2,
    totalGoals: 3,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 2,
    halfTimeGoals: 3,
    secondHalfGoals: 0,
    homeFormation: '352',
    awayFormation: '4231',
    btts: 1
  },
  {
    homeTeam: 'Modena',
    awayTeam: 'Como',
    homeGoals: 5,
    awayGoals: 1,
    totalGoals: 6,
    homeHalfTimeGoals: 3,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 3,
    secondHalfGoals: 3,
    homeFormation: '442',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Palermo',
    awayTeam: 'Pisa',
    homeGoals: 3,
    awayGoals: 3,
    totalGoals: 6,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 3,
    secondHalfGoals: 3,
    homeFormation: '343',
    awayFormation: '4231',
    btts: 1
  },
  {
    homeTeam: 'Parma',
    awayTeam: 'Reggina',
    homeGoals: 2,
    awayGoals: 0,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 2,
    homeFormation: '4231',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Venezia',
    awayTeam: 'Frosinone',
    homeGoals: 1,
    awayGoals: 3,
    totalGoals: 4,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 3,
    homeFormation: '352',
    awayFormation: '4231',
    btts: 1
  },
  {
    homeTeam: 'Como',
    awayTeam: 'Perugia',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '442',
    awayFormation: '4231',
    btts: 0
  },
  {
    homeTeam: 'Sudtirol',
    awayTeam: 'Benevento',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '343',
    btts: 1
  },
  {
    homeTeam: 'Frosinone',
    awayTeam: 'Spal',
    homeGoals: 2,
    awayGoals: 0,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 2,
    homeFormation: '4231',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Reggina',
    awayTeam: 'Cosenza',
    homeGoals: 3,
    awayGoals: 0,
    totalGoals: 3,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 2,
    homeFormation: '433',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Ascoli',
    awayTeam: 'Modena',
    homeGoals: 1,
    awayGoals: 2,
    totalGoals: 3,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 2,
    homeFormation: '352',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Brescia',
    awayTeam: 'Cittadella',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '433',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Pisa',
    awayTeam: 'Parma',
    homeGoals: 0,
    awayGoals: 0,
    totalGoals: 0,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 0,
    homeFormation: '4231',
    awayFormation: '4231',
    btts: 0
  },
  {
    homeTeam: 'Ternana',
    awayTeam: 'Palermo',
    homeGoals: 3,
    awayGoals: 0,
    totalGoals: 3,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 3,
    homeFormation: '433',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Venezia',
    awayTeam: 'Bari',
    homeGoals: 1,
    awayGoals: 2,
    totalGoals: 3,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 3,
    homeFormation: '352',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Genoa',
    awayTeam: 'Cagliari',
    homeGoals: 0,
    awayGoals: 0,
    totalGoals: 0,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 0,
    homeFormation: '4231',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Benevento',
    awayTeam: 'Ascoli',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '343',
    awayFormation: '352',
    btts: 1
  },
  {
    homeTeam: 'Perugia',
    awayTeam: 'Pisa',
    homeGoals: 1,
    awayGoals: 3,
    totalGoals: 4,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 3,
    homeFormation: '352',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Bari',
    awayTeam: 'Brescia',
    homeGoals: 6,
    awayGoals: 2,
    totalGoals: 8,
    homeHalfTimeGoals: 3,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 3,
    secondHalfGoals: 5,
    homeFormation: '442',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Cagliari',
    awayTeam: 'Venezia',
    homeGoals: 1,
    awayGoals: 4,
    totalGoals: 5,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 4,
    homeFormation: '433',
    awayFormation: '352',
    btts: 1
  },
  {
    homeTeam: 'Cittadella',
    awayTeam: 'Ternana',
    homeGoals: 0,
    awayGoals: 2,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Modena',
    awayTeam: 'Reggina',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Palermo',
    awayTeam: 'Sudtirol',
    homeGoals: 0,
    awayGoals: 1,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '4231',
    awayFormation: '352',
    btts: 0
  },
  {
    homeTeam: 'Parma',
    awayTeam: 'Frosinone',
    homeGoals: 2,
    awayGoals: 1,
    totalGoals: 3,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 2,
    homeFormation: '4231',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Spal',
    awayTeam: 'Genoa',
    homeGoals: 0,
    awayGoals: 2,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '4231',
    btts: 0
  },
  {
    homeTeam: 'Cosenza',
    awayTeam: 'Como',
    homeGoals: 3,
    awayGoals: 1,
    totalGoals: 4,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 3,
    secondHalfGoals: 1,
    homeFormation: '4231',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Ternana',
    awayTeam: 'Perugia',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '433',
    awayFormation: '352',
    btts: 0
  },
  {
    homeTeam: 'Genoa',
    awayTeam: 'Modena',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '433',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Ascoli',
    awayTeam: 'Parma',
    homeGoals: 1,
    awayGoals: 3,
    totalGoals: 4,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 2,
    halfTimeGoals: 2,
    secondHalfGoals: 2,
    homeFormation: '433',
    awayFormation: '4231',
    btts: 1
  },
  {
    homeTeam: 'Cagliari',
    awayTeam: 'Bari',
    homeGoals: 0,
    awayGoals: 1,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 1,
    homeFormation: '433',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Como',
    awayTeam: 'Spal',
    homeGoals: 3,
    awayGoals: 3,
    totalGoals: 6,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 2,
    secondHalfGoals: 4,
    homeFormation: '442',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Frosinone',
    awayTeam: 'Palermo',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '433',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Reggina',
    awayTeam: 'Cittadella',
    homeGoals: 3,
    awayGoals: 0,
    totalGoals: 3,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 2,
    homeFormation: '433',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Sudtirol',
    awayTeam: 'Cosenza',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '4231',
    btts: 1
  },
  {
    homeTeam: 'Venezia',
    awayTeam: 'Pisa',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 2,
    secondHalfGoals: 0,
    homeFormation: '343',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Brescia',
    awayTeam: 'Benevento',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 1,
    homeFormation: '4231',
    awayFormation: '4231',
    btts: 0
  },
  {
    homeTeam: 'Spal',
    awayTeam: 'Venezia',
    homeGoals: 2,
    awayGoals: 0,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Perugia',
    awayTeam: 'Ascoli',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '352',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Benevento',
    awayTeam: 'Cagliari',
    homeGoals: 0,
    awayGoals: 2,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 2,
    homeFormation: '352',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Cittadella',
    awayTeam: 'Frosinone',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Como',
    awayTeam: 'Sudtirol',
    homeGoals: 0,
    awayGoals: 2,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 2,
    homeFormation: '442',
    awayFormation: '352',
    btts: 0
  },
  {
    homeTeam: 'Cosenza',
    awayTeam: 'Bari',
    homeGoals: 0,
    awayGoals: 1,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '4231',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Modena',
    awayTeam: 'Brescia',
    homeGoals: 1,
    awayGoals: 3,
    totalGoals: 4,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 2,
    secondHalfGoals: 2,
    homeFormation: '442',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Parma',
    awayTeam: 'Ternana',
    homeGoals: 2,
    awayGoals: 3,
    totalGoals: 5,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 4,
    homeFormation: '4231',
    awayFormation: '541',
    btts: 1
  },
  {
    homeTeam: 'Pisa',
    awayTeam: 'Reggina',
    homeGoals: 0,
    awayGoals: 1,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '433',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Palermo',
    awayTeam: 'Genoa',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 1,
    homeFormation: '433',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Sudtirol',
    awayTeam: 'Pisa',
    homeGoals: 2,
    awayGoals: 1,
    totalGoals: 3,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 2,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Genoa',
    awayTeam: 'Parma',
    homeGoals: 3,
    awayGoals: 3,
    totalGoals: 6,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 2,
    halfTimeGoals: 4,
    secondHalfGoals: 2,
    homeFormation: '442',
    awayFormation: '4231',
    btts: 1
  },
  {
    homeTeam: 'Ascoli',
    awayTeam: 'Cittadella',
    homeGoals: 0,
    awayGoals: 0,
    totalGoals: 0,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 0,
    homeFormation: '433',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Bari',
    awayTeam: 'Spal',
    homeGoals: 2,
    awayGoals: 2,
    totalGoals: 4,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 2,
    secondHalfGoals: 2,
    homeFormation: '442',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Brescia',
    awayTeam: 'Perugia',
    homeGoals: 2,
    awayGoals: 1,
    totalGoals: 3,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 3,
    secondHalfGoals: 0,
    homeFormation: '433',
    awayFormation: '352',
    btts: 1
  },
  {
    homeTeam: 'Frosinone',
    awayTeam: 'Como',
    homeGoals: 2,
    awayGoals: 0,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '4231',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Reggina',
    awayTeam: 'Palermo',
    homeGoals: 3,
    awayGoals: 0,
    totalGoals: 3,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 2,
    homeFormation: '433',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Ternana',
    awayTeam: 'Cosenza',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '433',
    awayFormation: '4231',
    btts: 1
  },
  {
    homeTeam: 'Venezia',
    awayTeam: 'Benevento',
    homeGoals: 0,
    awayGoals: 2,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 2,
    homeFormation: '433',
    awayFormation: '352',
    btts: 0
  },
  {
    homeTeam: 'Cagliari',
    awayTeam: 'Modena',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '433',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Como',
    awayTeam: 'Brescia',
    homeGoals: 0,
    awayGoals: 1,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '442',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Benevento',
    awayTeam: 'Frosinone',
    homeGoals: 2,
    awayGoals: 1,
    totalGoals: 3,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 2,
    homeFormation: '352',
    awayFormation: '4231',
    btts: 1
  },
  {
    homeTeam: 'Cittadella',
    awayTeam: 'Venezia',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 2,
    homeFormation: '442',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Parma',
    awayTeam: 'Cosenza',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '4231',
    awayFormation: '4231',
    btts: 0
  },
  {
    homeTeam: 'Perugia',
    awayTeam: 'Bari',
    homeGoals: 1,
    awayGoals: 3,
    totalGoals: 4,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 3,
    homeFormation: '352',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Pisa',
    awayTeam: 'Genoa',
    homeGoals: 0,
    awayGoals: 1,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '433',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Reggina',
    awayTeam: 'Sudtirol',
    homeGoals: 4,
    awayGoals: 0,
    totalGoals: 4,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 2,
    secondHalfGoals: 2,
    homeFormation: '433',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Modena',
    awayTeam: 'Ternana',
    homeGoals: 4,
    awayGoals: 1,
    totalGoals: 5,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 2,
    secondHalfGoals: 3,
    homeFormation: '433',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Palermo',
    awayTeam: 'Ascoli',
    homeGoals: 2,
    awayGoals: 3,
    totalGoals: 5,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 2,
    halfTimeGoals: 3,
    secondHalfGoals: 2,
    homeFormation: '4231',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Spal',
    awayTeam: 'Cagliari',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '442',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Cagliari',
    awayTeam: 'Cittadella',
    homeGoals: 2,
    awayGoals: 1,
    totalGoals: 3,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 2,
    homeFormation: '433',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Cosenza',
    awayTeam: 'Modena',
    homeGoals: 2,
    awayGoals: 1,
    totalGoals: 3,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 2,
    homeFormation: '4231',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Frosinone',
    awayTeam: 'Brescia',
    homeGoals: 3,
    awayGoals: 0,
    totalGoals: 3,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 2,
    homeFormation: '4231',
    awayFormation: '442',
    btts: 0
  },
  {
    homeTeam: 'Pisa',
    awayTeam: 'Como',
    homeGoals: 2,
    awayGoals: 2,
    totalGoals: 4,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 2,
    secondHalfGoals: 2,
    homeFormation: '433',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Sudtirol',
    awayTeam: 'Venezia',
    homeGoals: 1,
    awayGoals: 2,
    totalGoals: 3,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 3,
    homeFormation: '433',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Ternana',
    awayTeam: 'Reggina',
    homeGoals: 1,
    awayGoals: 0,
    totalGoals: 1,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '433',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Ascoli',
    awayTeam: 'Spal',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 2,
    secondHalfGoals: 0,
    homeFormation: '433',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Genoa',
    awayTeam: 'Benevento',
    homeGoals: 0,
    awayGoals: 0,
    totalGoals: 0,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 0,
    homeFormation: '442',
    awayFormation: '352',
    btts: 0
  },
  {
    homeTeam: 'Perugia',
    awayTeam: 'Parma',
    homeGoals: 0,
    awayGoals: 0,
    totalGoals: 0,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 0,
    homeFormation: '352',
    awayFormation: '4231',
    btts: 0
  },
  {
    homeTeam: 'Bari',
    awayTeam: 'Palermo',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '4231',
    btts: 1
  },
  {
    homeTeam: 'Ascoli',
    awayTeam: 'Ternana',
    homeGoals: 2,
    awayGoals: 1,
    totalGoals: 3,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 2,
    secondHalfGoals: 1,
    homeFormation: '433',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Benevento',
    awayTeam: 'Cosenza',
    homeGoals: 0,
    awayGoals: 1,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 0,
    secondHalfGoals: 1,
    homeFormation: '433',
    awayFormation: '4231',
    btts: 0
  },
  {
    homeTeam: 'Brescia',
    awayTeam: 'Sudtirol',
    homeGoals: 2,
    awayGoals: 0,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '443',
    awayFormation: '433',
    btts: 0
  },
  {
    homeTeam: 'Modena',
    awayTeam: 'Frosinone',
    homeGoals: 0,
    awayGoals: 1,
    totalGoals: 1,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 0,
    homeFormation: '442',
    awayFormation: '4231',
    btts: 0
  },
  {
    homeTeam: 'Spal',
    awayTeam: 'Reggina',
    homeGoals: 1,
    awayGoals: 3,
    totalGoals: 4,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 3,
    homeFormation: '442',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Venezia',
    awayTeam: 'Genoa',
    homeGoals: 1,
    awayGoals: 2,
    totalGoals: 3,
    homeHalfTimeGoals: 0,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 1,
    secondHalfGoals: 2,
    homeFormation: '433',
    awayFormation: '442',
    btts: 1
  },
  {
    homeTeam: 'Cittadella',
    awayTeam: 'Pisa',
    homeGoals: 4,
    awayGoals: 3,
    totalGoals: 7,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 1,
    halfTimeGoals: 2,
    secondHalfGoals: 5,
    homeFormation: '442',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Como',
    awayTeam: 'Cagliari',
    homeGoals: 1,
    awayGoals: 1,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '442',
    awayFormation: '433',
    btts: 1
  },
  {
    homeTeam: 'Palermo',
    awayTeam: 'Perugia',
    homeGoals: 2,
    awayGoals: 0,
    totalGoals: 2,
    homeHalfTimeGoals: 1,
    awayHalfTimeGoals: 0,
    halfTimeGoals: 1,
    secondHalfGoals: 1,
    homeFormation: '4231',
    awayFormation: '352',
    btts: 0
  },
  {
    homeTeam: 'Parma',
    awayTeam: 'Bari',
    homeGoals: 2,
    awayGoals: 2,
    totalGoals: 4,
    homeHalfTimeGoals: 2,
    awayHalfTimeGoals: 2,
    halfTimeGoals: 4,
    secondHalfGoals: 0,
    homeFormation: '4231',
    awayFormation: '433',
    btts: 1
  }


]